sudo:
  - false

language:
  - swift

matrix:
  include:
    - name: "OS X"
      os: osx
      osx_image: xcode10.1

    - name: "Linux"
      os: linux
      dist: xenial
      services:
        - mysql
      before_script:
        - wget https://swift.org/builds/swift-4.2.2-release/ubuntu1604/swift-4.2.2-RELEASE/swift-4.2.2-RELEASE-ubuntu16.04.tar.gz
        - tar xzf swift-4.2.2-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-4.2.2-RELEASE-ubuntu16.04/usr/bin:"${PATH}"

script:
  - swift test
