sudo:
  - false

matrix:
  include:
    - name: "OS X"
      os: osx
      osx_image: xcode10.1
      language: swift
      script:
        - swift test

    - name: "Linux"
      os: linux
      dist: xenial
      language: c
      services:
        - mysql
      before_script:
        - wget https://swift.org/builds/swift-4.2.2-release/ubuntu1604/swift-4.2.2-RELEASE/swift-4.2.2-RELEASE-ubuntu16.04.tar.gz
        - tar xzf swift-4.2.2-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-4.2.2-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
      script:
        - swift test

    - name: "Check Linux Test Cases"
      os: osx
      osx_image: xcode10.1
      language: swift
      script:
        - swift test --generate-linuxmain
        - git diff # Appears to be necessary for the next check to work as expected.
        - |
          if ! git diff-index --quiet HEAD --; then
            echo "Linux tests are out of date. Please run the following command:"
            echo
            echo "    swift test --generate-linuxmain"
            exit 1
          fi
