sudo:
  - false

matrix:
  include:
    - name: "OS X Xcode 10.1"
      os: osx
      osx_image: xcode10.1
      language: swift
      script:
        - swift test

    - name: "Linux Swift 4.2.2"
      os: linux
      dist: xenial
      language: c
      services:
        - mysql
      env:
        - MYSQL_SERVER_HOST=localhost
        - MYSQL_SERVER_PORT=3306
        - MYSQL_SERVER_USER="root"
        - MYSQL_SERVER_PASSWORD=""
      before_script:
        - wget https://swift.org/builds/swift-4.2.2-release/ubuntu1604/swift-4.2.2-RELEASE/swift-4.2.2-RELEASE-ubuntu16.04.tar.gz
        - tar xzf swift-4.2.2-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-4.2.2-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
        - swift --version
      script:
        - swift test

    - name: "Linux Swift latest"
      os: linux
      dist: xenial
      language: c
      services:
        - mysql
      env:
        - MYSQL_SERVER_HOST=localhost
        - MYSQL_SERVER_PORT=3306
        - MYSQL_SERVER_USER="root"
        - MYSQL_SERVER_PASSWORD=""
      before_script:
        - wget "https://swift.org/builds/development/ubuntu1604/swift-DEVELOPMENT-SNAPSHOT-2019-02-03-a/swift-DEVELOPMENT-SNAPSHOT-2019-02-03-a-ubuntu16.04.tar.gz" -O swift-latest.tar.gz
        - tar xzf swift-latest.tar.gz
        - export PATH=$(pwd)/swift-latest/usr/bin:"${PATH}"
        - swift --version
      script:
        - swift test

# This job is unfortunately flaky because swift test --generate-linuxmain doesn't generate values in sorted
# order. See https://bugs.swift.org/browse/SR-9872 for bug tracking resolution of this.
#    - name: "Check Linux Test Cases"
#      os: osx
#      osx_image: xcode10.1
#      language: swift
#      script:
#        - swift test --generate-linuxmain
#        - git diff # Appears to be necessary for the next check to work as expected.
#        - |
#          if ! git diff-index --quiet HEAD --; then
#            echo "Linux tests are out of date. Please run the following command:"
#            echo
#            echo "    swift test --generate-linuxmain"
#            exit 1
#          fi
