name: presubmit
on:
  pull_request:
    branches:
      - develop

jobs:
  # mac_test:
  #   runs-on: macOS-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - run: swift test

  linux_test:
    container:
      image: swift:5.2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql_package: ["https://downloads.mysql.com/archives/get/p/23/file/mysql-community-server_5.7.29-1ubuntu18.04_i386.deb"]
    steps:
      - run: apt-get update && apt-get install -y libssl-dev
      - uses: actions/checkout@v2
      - run: swift run --enable-test-discovery bootstrap "${{ matrix.mysql_package }}" && swift test --enable-test-discovery --enable-code-coverage
      - uses: mattpolzin/swift-codecov-action@0.4.0
  #
  # lint:
  #   container:
  #     image: swift:5.2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: apt-get update && apt-get install -y libssl-dev
  #     - uses: actions/checkout@v2
  #     - name: Run SwiftLint
  #       uses: norio-nomura/action-swiftlint@3.1.0
  #       with:
  #         args: --strict
