name: presubmit
on:
  pull_request:
    branches:
      - develop

jobs:
  # mac_test:
  #   runs-on: macOS-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - run: swift test

  linux_test:
    container:
      image: swift:5.2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server_version: [mysql:5.7]
    steps:
      - run: apt-get update && apt-get install -y libssl-dev
      - uses: actions/checkout@v2
      - run: swift test --enable-test-discovery --enable-code-coverage
      - uses: mattpolzin/swift-codecov-action@0.4.0
    services:
      mysql:
        image: ${{ matrix.server_version }}
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: 
  #
  # lint:
  #   container:
  #     image: swift:5.2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: apt-get update && apt-get install -y libssl-dev
  #     - uses: actions/checkout@v2
  #     - name: Run SwiftLint
  #       uses: norio-nomura/action-swiftlint@3.1.0
  #       with:
  #         args: --strict
